### ISSUE TITLE
[bug] AttributeError: module 'bcrypt' has no attribute 'hashpw'

### ISSUE THREAD

**Issue by janoskabedis** [signebedi/libreforms-fastapi#184]
This error may occur because we are lacking certain OS-level dependencies, see https://stackoverflow.com/a/65673374. These are defined at the following address: https://pypi.org/project/bcrypt/.

**Comment by signebedi** [comment]
I think this may be our clarion call to use Scrypt instead... saving ourselves from the bcrypt dependency, since scrypt ships with cryptography anyways. https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/#cryptography.hazmat.primitives.kdf.scrypt.Scrypt
