### ISSUE TITLE
Display a list of forms after a user has logged on

### ISSUE THREAD

**Issue by wcj365** [signebedi/libreforms-fastapi#227]
After a user logs on.
Display a list of all forms that the user has saved/submitted.
Show key fields including date created, last modified, status)
Include a link to the form so user can directly access the form and make updates.

**Comment by signebedi** [comment]
This sounds something like a "recent activity" feature. It's reasonable and straightforward to implement. Not all admins may want it, so we can make it a config like RECENT_ACTIVITY_ENABLED, which should default to False. https://github.com/signebedi/libreforms-fastapi/blob/master/libreforms_fastapi/utils/config.py.

Then, we want to modify the home jinja2 template. Currently, it's very straightforward. https://github.com/signebedi/libreforms-fastapi/blob/master/libreforms_fastapi/app/templates/home.html.jinja. It has access to the config object, so you can access the config we set above as `config.RECENT_ACTIVITY_ENABLED`.

Then, we want to pull the API data using Ajax (the endpoint will be /api/form/read_all) and render ~5 of the most recent changes in a data table, see eg. below.

```
$('#recentActivityTable').DataTable({
    "ordering": false,
    "info": false,
    "paging": false,
    "searching": false 
});

```

**Comment by signebedi** [comment]
[api] Allow sorting of read_all by last_edited date
If we want to see recent activity, we should add a param to this API endpoint to sort results by last edited date, with most recent edits going to the top of the results.

**Comment by signebedi** [comment]
We'll leave in pagination to the datatable for now, but it may make sense to remove that option from the UI datatable down the road. The broader question is whether we should be able to set the length read_all API call as a param.

**Comment by signebedi** [comment]
[api] [form] Add set_length int param to read_all API endpoint
We may want to limit responses this way. But then we want to make it easier to orderBy some field to enable appropriate control over the data returned...
