### ISSUE TITLE
add an example of a prohibited value validator to the documentation

### ISSUE THREAD

**Issue by rl-utility-man** [signebedi/libreforms-fastapi#243]
Consider a situation where the form presents the user e.g.  with a drop down that defaults to "SELECT", but then contains valid values of "Apple", "Banana" and "Chow fun."  We want the form processor to reject forms submitted with a value of "SELECT."  Perhaps we'd also want the form processor to reject "apple" and "banana" if a second field indicates that the food contains sauce.

My understanding is that at least an unequal to validator is supported, but there's no example of it in the documentation.

Similarly, if a greater than validator is supported, consider giving an example of that -- say with greater than 0:

https://github.com/libreForms/spec/blob/main/spec.md#yaml

**Comment by signebedi** [comment]
Underneath the hood, we use pydantic Fields to manage form field metadata, see https://docs.pydantic.dev/latest/concepts/fields/. 

This supports greater than, less than, greater than or equal to, and less than or equal to params for number fields; it also supports regex patterns, max length, and min length for string fields. We explicitly implement these in the UI when we generate HTML for the client form here: https://github.com/signebedi/libreforms-fastapi/blob/aef3fb945c41519e39b826c3314eee1f1ce33695/libreforms_fastapi/utils/pydantic_models.py#L530.

However, you could in theory pass any Field params under the validators options - these are used to generate the pydantic model to validate data when it makes it through the client to the backend, see https://github.com/signebedi/libreforms-fastapi/blob/aef3fb945c41519e39b826c3314eee1f1ce33695/libreforms_fastapi/utils/pydantic_models.py#L470. In fact, this is probably a more powerful way to do data validation.

I think you could probably pass a `pattern: "^(?!SELECT$).*"` option to these select fields and these should correctly validate data on the backend, but it is likely that the client will not prevent submission of these values.
