### ISSUE TITLE
Add some kind of support for plotly

### ISSUE THREAD

**Issue by janoskabedis** [signebedi/libreforms-fastapi#247]
https://github.com/signebedi/libreforms-fastapi/blob/0b8a718af9dafcfbf9eda93acabe969e4479081e/requirements/data.txt#L2

Add the requirement. Consider whether plotly graphics should be within the scope of the form config, or whether we should allow users to generate visualizations with a simplified option set and store these in a database table.

**Comment by signebedi** [comment]
We should really consider whether this is the path we want to go down. More features increase complexity and work against maintainability and, in the worst cases, site stability. As such, we should consider whether it is more appropriate to direct users to other visualization tools like Plotly or Grafana.
