### ISSUE TITLE
Add method for linking to user profile by username

### ISSUE THREAD

**Issue by janoskabedis** [signebedi/libreforms-fastapi#268]
Right now, you can only access user profiles in the UI using User IDs. However, often we only have access to the username - not the User ID - and want to link to the user's profile... 

Is there a way to make it configurable to enable a proxy route that use's usernames? And then redirects to the user profile?

**Comment by signebedi** [comment]
This is a good feature to add because we will be able to add hyperlinks to various pages - like the read_one form page, and all the pages where we list multiple forms.

**Comment by signebedi** [comment]
Closing, but this may produce strange results when other profiles are not enabled - in which case, we can probably just disable the links...
